-- Elite Med: sharhlar jadvali
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 80),
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(trim(comment)) between 3 and 1000),
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

-- Saytga kirganlar tasdiqlangan sharhlarni o'qiy oladi.
drop policy if exists "Public can read reviews" on public.reviews;
create policy "Public can read reviews"
on public.reviews
for select
to anon, authenticated
using (true);

-- Saytga kirganlar yangi sharh yubora oladi.
drop policy if exists "Public can add reviews" on public.reviews;
create policy "Public can add reviews"
on public.reviews
for insert
to anon, authenticated
with check (true);

-- UPDATE/DELETE policy ataylab yo'q: oddiy sayt foydalanuvchisi sharhni o'zgartira/o'chira olmaydi.
